### PR TITLE
Shrink the Gather's output shape

### PR DESCRIPTION
**Pull request by mingmingtasd**
Shrink the Gather's output shape to avoid crash in AddGemm(). For example:

Gather output shape {1, 1, 256} -> shrink to 2d {1, 256}.  Gemm can only support 2d inputs now.

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
Thanks Mingming.

Interesting 🤔. There are a number of places where I'm passing the modified output tensor desc to CreateNodeOutput. I'll need to review each of these cases...

```
GraphDMLImpl::AddInstanceNormalization(...)
...
  output_tensor_desc.PermuteDimensions(tensor_dimensions_permutation, TensorDesc::Alignment::kTrailing);
...
  auto node_output = graph_desc_builder_->CreateNodeOutput(
      node, 0, std::move(output_tensor_desc));
```

**Comment by mingmingtasd** [comment]
> Thanks Mingming.
> 
> Interesting 🤔. There are a number of places where I'm passing the modified output tensor desc to CreateNodeOutput. I'll need to review each of these cases...
> 
> ```
> GraphDMLImpl::AddInstanceNormalization(...)
> ...
>   output_tensor_desc.PermuteDimensions(tensor_dimensions_permutation, TensorDesc::Alignment::kTrailing);
> ...
>   auto node_output = graph_desc_builder_->CreateNodeOutput(
>       node, 0, std::move(output_tensor_desc));
> ```

Yes, all nodes need to be checked again. If the output shape has been reset in graph_dml_impl.cc and mismatch with the graph builder level, it's dangerous and will let device_->CreateOperator(&op_desc, IID_PPV_ARGS(&op)) fail. You can refer to the https://github.com/mingmingtasd/webnn-native/blob/dml_optimize/src/webnn/native/dml/GraphDML.cpp, you can see, I ensure the output shape can align with the graph builder level.

**Comment by mingmingtasd** [comment]
I mean aligning with graph builder level equals to webnn spec, anyway, we need to keep a specific shape for each node no matther which backend/implementation actually give.

**Comment by fdwr** [comment]
Indeed. The reason it works as-is for so many operators is because the input and output shapes were the same anyway, or the output shape between DML and WebNN/ONNX were the same. So, this really hits operators where the necessary DML shape and the WebNN/ONNX size differ. My single operator tests would not have caught these because it shows the client-side builder shape, not the internal shape, and this is the first time we've glued together so many operators together.

**Pull request merged**
